mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    gen_lyap.c

mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    gen_care.c

mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    mincost_ngrad.c 

mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    rand_mat.c

mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    rand_orth.c

mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    rand_sym.c

mex -v COMPFLAGS='$COMPFLAGS /Qstd=c99 /Qrestrict /Qopenmp /Qx:SKYLAKE /DMKL_ILP64 -I"$CROOT"\mkl\include -I..\include'...
    LINKFLAGS='$LINKFLAGS /NODEFAULTLIB:libcmt /LIBPATH:..\lib controlsim.lib slicot.lib lpkaux.lib mkl_intel_ilp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib'...
    rand_perturb.c
